# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "immutable-4.0.0-rc.12" = {
      name = "immutable";
      packageName = "immutable";
      version = "4.0.0-rc.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-4.0.0-rc.12.tgz";
        sha512 = "0M2XxkZLx/mi3t8NVwIm1g8nHoEmM9p9UBl/G9k4+hm0kBgOVdMV/B3CY5dQ8qG8qc80NN4gDV4HQv6FTJ5q7A==";
      };
    };
    "query-string-6.12.1" = {
      name = "query-string";
      packageName = "query-string";
      version = "6.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-6.12.1.tgz";
        sha512 = "OHj+zzfRMyj3rmo/6G8a5Ifvw3AleL/EbcHMD27YA31Q+cO5lfmQxECkImuNVjcskLcvBRVHNAB3w6udMs1eAA==";
      };
    };
    "split-on-first-1.1.0" = {
      name = "split-on-first";
      packageName = "split-on-first";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split-on-first/-/split-on-first-1.1.0.tgz";
        sha512 = "43ZssAJaMusuKWL8sKUBQXHWOpq8d6CfN/u1p4gUzfJkM05C8rxTmYrkIPTXapZpORA6LkkzcUulJ8FqA7Uudw==";
      };
    };
    "strict-uri-encode-2.0.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-2.0.0.tgz";
        sha1 = "b9c7330c7042862f6b142dc274bbcc5866ce3546";
      };
    };
  };
  args = {
    name = "js-encryptedfs";
    packageName = "js-encryptedfs";
    version = "0.0.1";
    src = ./..;
    dependencies = [
      sources."decode-uri-component-0.2.0"
      sources."immutable-4.0.0-rc.12"
      sources."query-string-6.12.1"
      sources."split-on-first-1.1.0"
      sources."strict-uri-encode-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Encrypted filesystem written in TypeScript for Node.js";
      homepage = "https://github.com/MatrixAI/js-encryptedfs#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}